language: r
sudo: required
dist: trusty
cache: packages
r_check_args: "--as-cran"
addons:
  apt:
    packages:
      - libssh-dev
r_packages:
  - covr
  - devtools
after_success:
 - R -e 'covr::codecov()'
